### ISSUE TITLE
Applying my changes (user-overrides.js)

### ISSUE THREAD

**Issue by zdat** [HorlogeSkynet/thunderbird-user.js#10]
Was wondering if there's anything in place to apply changes (using a user-overrides.js) [like there is in ghacks](https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.2-Applying-Your-Changes).

Don't mind editing the user.js manually but I like doing it this way.

**Comment by HorlogeSkynet** [comment]
Hey over here ! This is definitely related to #1.
It's a "help wanted" subject, if you are willing to contribute (upstream) it would be awesome.
Bye 👋

**Comment by HorlogeSkynet** [comment]
Closing here, let's use #1 for further discussions if you don't mind.
