### ISSUE TITLE
Missing semicolons

### ISSUE THREAD

**Issue by wickedsp1d3r** [HorlogeSkynet/thunderbird-user.js#11]
Hey,
A few lines are missing an ending semicolon. I think the produced user.js remains incomplete because of this.

At least these have this issue:
```
user_pref("mail.instrumentation.postUrl", "")
user_pref("mail.instrumentation.askUser", false)
user_pref("mail.instrumentation.userOptedIn", false)
```

**Comment by HorlogeSkynet** [comment]
Thanks for reporting this @wickedsp1d3r !
It looks like there is (at least) a limitation to Acorn usage about linting this project...

**Comment by HorlogeSkynet** [comment]
This is it @wickedsp1d3r, what happened shouldn't happen again with new linting procedure :tada:
<https://github.com/HorlogeSkynet/thunderbird-user.js/actions>
