### ISSUE TITLE
[BUG] dom.IntersectionObserver.enabled = false breaks dev console (linux)

### ISSUE THREAD

**Issue by atomGit** [HorlogeSkynet/thunderbird-user.js#13]
'dom.IntersectionObserver.enabled' 'false' breaks the developer console (console is empty) on Linux

can someone confirm?

TB 78.4.3
OS: Manjaro/Arch

**Comment by HorlogeSkynet** [comment]
You're right, I could manage to reproduce (Linux + Windows).
Let's leave this enabled by default then :bow:
