### ISSUE TITLE
[BUG] line 1115 missing comment close

### ISSUE THREAD

**Issue by atomGit** [HorlogeSkynet/thunderbird-user.js#16]
* date: 28 August 2021
* version: v78.0

line 1115 missing comment close...

`/* 2802: enable Thunderbird to clear items on shutdown (see 2803)`

therefore 1116 is not read ( `user_pref("privacy.sanitize.sanitizeOnShutdown", true);` )

**Comment by HorlogeSkynet** [comment]
Good catch @atomGit, I'm fixing this and drafting a 78.1 release :+1:
