### ISSUE TITLE
[RFC] Outgoing email addresses collection deactivation

### ISSUE THREAD

**Issue by atomGit** [HorlogeSkynet/thunderbird-user.js#17]
* date: 28 August 2021
* version: v78.0

user_pref("mail.collect_addressbook", "");
user_pref("mail.collect_email_address_outgoing", false);

don't know that i agree with these - my thinking is...

* first off it's redundant - i don't see the need for the first pref if the latter is used
* that prefs which are easily available in the UI generally shouldn't be added to user.js since it removes user choice and could result in unexpected behavior if user didn't diff the files (updater.js -c on linux, i don't know about wintendo)
* privacy-wise this solves nothing in a multi-user env. unless it's a fresh profile - collected addresses still exist and are still accessible

**Comment by HorlogeSkynet** [comment]
* I guess that was a "defense in depth" approach (upstream gHacks-User.JS was known to disable _all_ prefs related to a specific feature, it is still the case with Arkenfox
* I actually don't agree with this one : users have to understand that those "scripts" are **templates**, actually hard-tweaking the whole software, and possibly overwriting their own configuration in the resulting `prefs.js`
* I agree here, but I often assume our audience is "users with fresh profiles" (or at least an interesting target, maybe is it recommended somewhere in the Wikis ?)

The blame is :
```
 68d3683 (Samuel FORESTIER  Tue Nov 03 10:59:41 2020) user_pref("mail.collect_addressbook", "");  // [DEFAULT: "jsaddrbook://history.sqlite"]
^7973d8a (Daniel Gray       Sun Nov 24 01:00:00 2019) user_pref("mail.collect_email_address_outgoing", false);
```

My commit was actually a fix, as the value type was originally incorrect for `mail.collect_addressbook` :

```patch
commit 68d36833f780ca2a88481868d79bfde37de83741
Author: Samuel FORESTIER <dev@samuel.domains>
Date:   Tue Nov 3 10:59:41 2020 +0100

    Fixes wrong value type set for `mail.collect_addressbook` option...
      and adds the default value to template for re-enabling purposes

diff --git a/user.js b/user.js
index 5e2708e..e4b6664 100644
--- a/user.js
+++ b/user.js
@@ -1473,7 +1473,7 @@ user_pref("mailnews.display.date_senders_timezone", false);
 /* 6007: Address book collection
  * [SETUP-FEATURE] Disable address book email collection
  * Consider using https://addons.thunderbird.net/addon/cardbook instead ***/
-user_pref("mail.collect_addressbook", false);
+user_pref("mail.collect_addressbook", "");  // [DEFAULT: "jsaddrbook://history.sqlite"]
 user_pref("mail.collect_email_address_outgoing", false);
 
 /*** [SECTION 6100]: EMAIL COMPOSITION (ENCODING / FORMAT / VIEW)
```

---

Tell me what you think about that, and whether we should modify this for the (final ?) v78 version.
Bye :wave:

**Comment by atomGit** [comment]
i don't have a hard opinion so whatever you decide is fine

mail.collect_addressbook isn't a network address so personally i wouldn't bother clearing it but it's up to you

**Comment by HorlogeSkynet** [comment]
See de8048f, closing here and drafting official v78.1 :bow:
