### ISSUE TITLE
[BUG] Broken Toolbar on macOS

### ISSUE THREAD

**Issue by tommytran732** [HorlogeSkynet/thunderbird-user.js#18]
**Describe the bug**

The toolbar looks extremely weird on macOS after installing user.js

**Expected behavior**
The toolbar looks normal

**Screenshots**
<img width="1024" alt="Screen Shot 2022-04-18 at 12 45 55 AM" src="https://user-images.githubusercontent.com/57488583/163756113-d4800374-451f-4c22-be09-5d91ccd7ef52.png">

**Environment**
- Thunderbird version used (X.Y.Z) : 91.8.0
- `thunderbird user.js` template version used (X.Y or commit SHA) : 78.1
- Operating system and version : macOS Monterey

**Checklist**
- [x] I can confirm the bug is due to `thunderbird user.js` **template** and not an overridden preference nor an add-on ;
- [x] I have searched for `[SETUP-*]` tags and read them up ;
- [x] I have searched the GitHub project (issues and Wiki) for my issue.

**Comment by tommytran732** [comment]
I just realized the WIP 91 PR fixes this. Closing.

**Comment by HorlogeSkynet** [comment]
Thanks for opening (and closing !) this. I was not aware of any actual _bug_ between the "v78 template" and more recent releases of TB (only that many preferences were missing / deprecated / redundant / irrelevant for obvious reasons).

Thus I'd prefer asking anyway : Were you on a "clean" profile when installing the v78.1 version ? If so, there might be a bug that I'll leave to the reader to encounter and fix (if they want) on this project version.

From what I see, it _could_ be an issue related to "dark mode" inconsistencies between TB and your system (skewing the colors palette).

Anyway, I've just merged #15 and published [a new protected branch targeting TB ESR v78](https://github.com/HorlogeSkynet/thunderbird-user.js/tree/version/78-esr), certainly opened to pull requests for these specific cases.

Thanks, bye 👋

**Comment by tommytran732** [comment]
Yeah, it was a fresh install of Thunderbird
