### ISSUE TITLE
Few suggestions 

### ISSUE THREAD

**Issue by giving-sesame** [HorlogeSkynet/thunderbird-user.js#19]
Hi! Thank you for great work! I would like to suggest few changes:

1. Add the following lines to remove Content-Language and Accept-Language headers - to improve privacy protection:
user_pref("mail.suppress_content_language", true);
user_pref("network.trr.send_accept-language_headers", false);

2. Add the explanation to
user_pref("privacy.resistFingerprinting", true);
that if this property is set to true, the user-agent override will not work

3. Add the explanation to
user_pref("general.useragent.override", "");
that empty value can break OAuth2 login to Microsoft Exchange

4. Add the following line:
user_pref("mail.compose.other.header", "header1,header2");
This creates custom headers, which values can be set in compose window. Then they will be added to the headers of sent message.

**Comment by HorlogeSkynet** [comment]
Hi @giving-sesame ! Many thanks for your message, you'll find below my quick review for of your suggestions :

1. For `mail.suppress_content_language`, you are right, from this [Tails issue](https://gitlab.tails.boum.org/tails/tails/-/issues/17148), it seems that it is missing (as well as `mail.sanitize_date_header`). I'll add them for 91 and 78 ESR. Notes to myself : added in [TB 52](https://bugzilla.mozilla.org/show_bug.cgi?id=1370217) and in [TB 76](https://bugzilla.mozilla.org/show_bug.cgi?id=1603359).
  For `network.trr.send_accept-language_headers`, [it defaults to `false`](https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#10598), and even [Arkenfox does not specify it](https://github.com/arkenfox/user.js/issues/869#issuecomment-570802521). I'd rather leave it alone too here. 
3. Actually, documentation (from upstream Arkenfox) [indicates that UA is spoofed](https://github.com/HorlogeSkynet/thunderbird-user.js/blob/f45c0a3d750ef4baecbd5a4d384627c122cdeadb/user.js#L948).
  On the other side, `general.useragent.override` section documentation ("NON-RFP") [already notes that they should not be used with RFP](https://github.com/HorlogeSkynet/thunderbird-user.js/blob/f45c0a3d750ef4baecbd5a4d384627c122cdeadb/user.js#L1278).
4. Do you have an external reference for this issue ? A quick Google query didn't bring up any relevant result.
5. OK !

Thanks again, bye :wave:

**Comment by giving-sesame** [comment]
3. This is my own experience. My company uses Microsoft Exchange via Office365 server. So in Thunderbird I have Owl addon to access it. Once I looked through the headers and did not like that my user-agent and languages are published there. I think it could be harmful. So I started looking for any solutions. At first I found mail.suppress_content_language and network.trr.send_accept-language_headers parameters. Then - your user.js.

I wanted to avoid publishing user-agent at all, so I left general.useragent.override empty. After starting TB I got error "The page isn't redirecting properly", address outlook.office.com/owa/auth. It took me some time to find the guilty parameter. I set it to "Generic" and everything is fine now.

**Comment by HorlogeSkynet** [comment]
Thanks again for your fast answer.

Do I have to assume RFP broke your OAuth against Microsoft Exchange ? Or maybe you didn't even enable it at first ?
If I don't misread you, without enabling it and with manually resetted User-Agent (using `general.useragent.override`) to prevent leakage, it didn't work.

> Note : from [ESR-78](https://searchfox.org/mozilla-esr78/source/dom/base/Navigator.cpp#1911) and [ESR-91](https://searchfox.org/mozilla-esr91/source/dom/base/Navigator.cpp#1933) sources, it seems this parameter is ignored when RFP is enforced.

Feel free to tell me I misunderstood your experience :pray:

**Comment by giving-sesame** [comment]
OAuth2 was active all the time on Microsoft Exchange. Then I found your user.js, edited it, activated user-agent override, and installed user.js. I did not enable RFP at first, because I was interested in user-agent and in google I read I have to disable RFP to deal with user-agent. To be clear, I made 2 experiments with empty user-agent right now:

This setup breaks login to Microsoft Exchange:
privacy.resistFingerprinting=false
general.useragent.override=""

This setup has no errors:
privacy.resistFingerprinting=true
general.useragent.override=""


---
My current working setup:
privacy.resistFingerprinting=false
general.useragent.override="Generic"

**Comment by HorlogeSkynet** [comment]
> OAuth2 was active all the time on Microsoft Exchange.

Yes ! I was mentioning RFP, and not OAuth :wink:

> I did not enable RFP at first, because I was interested in user-agent and in google I read I have to disable RFP to deal with user-agent.

Seems legit according to the snippets linked in my previous response !

> I made 2 experiments with empty user-agent right now:

Thanks, that's clear and what I had in mind.

---

So I'll edit the template to add a note about the issue you experienced :+1:
However, about :

> general.useragent.override="Generic"

I don't think it is a good idea to set your UA to something "unusual".
Indeed your _privacy_ would be improved as you prevent system info leakages, but it has to be leveraged by the fact that you _might_ be alone in this situation.
Also see [project (simplified) rationale](https://github.com/HorlogeSkynet/thunderbird-user.js/blob/3c70f084688566114fc97d250f3d5b870deb93d3/.github/ISSUE_TEMPLATE/change_request.md?plain=1#L29).

I would encourage you to enable RFP and let Mozilla's core handle User-Agent.

Bye :wave:

**Comment by giving-sesame** [comment]
I checked user-agent in sent messages.

privacy.resistFingerprinting=true makes "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
privacy.resistFingerprinting=false makes "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:91.0) Gecko/20100101 Thunderbird/91.9.0"

Not a big difference, but, well, maybe you are right, let the core handle it.

Thank you!

**Comment by HorlogeSkynet** [comment]
Please see above commits and tell me what you think !
If you're OK, I'll backport 50afdb9a57aeacd9f086f0a77fa731e308d0731a to v78-ESR.

Bye, thanks again ! :pray:

**Comment by giving-sesame** [comment]
Hi! Just for your information. Occasionally I found out some details regarding empty user agent string and Office365:

Microsoft bug in Office 365, introduced around 2019-08-27, where the login page fails with "OpenIdConnect" "ArgumentNullException".
