### ISSUE TITLE
RFP [4501] breaks colors settings

### ISSUE THREAD

**Issue by atomGit** [HorlogeSkynet/thunderbird-user.js#2]
this is just an FYI issue
`privacy.resistFingerprinting` = `true`

edit -> preferences -> display -> fonts & colors -> colors

text and background color options have no effect on message/preview pane and compose windows (at least not on Linux)

i suspect this problem is by design, but i opened a bug report anyway...
[1600074 - 'privacy.resistFingerprinting' breaks preview pane color options](https://bugzilla.mozilla.org/show_bug.cgi?id=1600074)

**Comment by HorlogeSkynet** [comment]
Thanks @atomGit, good catch.
Do you think we should disable RFP on the template meanwhile ?
Or at least, should we precise a link to the filled bug as a comment ?
Did you have it enabled (and working) on v60 ?

Thanks, bye 👋

**Comment by atomGit** [comment]
> Do you think we should disable RFP on the template meanwhile ?
no, i think RFP is more important than a UI glitch personally

> Or at least, should we precise a link to the filled bug as a comment ?
probably so - that offloads some of the responsibility to keep abreast of the issue to the user - either that, or perhaps add a generic "known issues" note in the .js and link to this issue on the repo - the latter is less work (fewer updates to .js), but i'm not sure it's the best way to go

> Did you have it enabled (and working) on v60 ?
negative - i'm gambling that with JS disabled and displaying mail in plain text or simple html is enough to resist most fingerprinting

**Comment by HorlogeSkynet** [comment]
Confirmed on Windows too.

**Comment by atomGit** [comment]
i see i was assigned to this issue - the dummy i am, you'll have to explain what you want me to do :)

**Comment by HorlogeSkynet** [comment]
Nothing but watching the bug you filled and keeping us up to speed about its progress 😉

**Comment by HorlogeSkynet** [comment]
Bug [confirmed](https://bugzilla.mozilla.org/show_bug.cgi?id=1600074#c3), setting `!upstream` here.
