### ISSUE TITLE
[WIKI] extension changes

### ISSUE THREAD

**Issue by atomGit** [HorlogeSkynet/thunderbird-user.js#22]
re: [4.1 Extensions](https://github.com/HorlogeSkynet/thunderbird-user.js/wiki/4.1-Extensions)

* Lightening - no longer needed since calendar integration
* Enigmail - no longer needed since PGP integration - i believe this is the case for Windows also???

**Comment by HorlogeSkynet** [comment]
Thanks for bringing this up @atomGit, please tell me whether [this page edition](https://github.com/HorlogeSkynet/thunderbird-user.js/wiki/4.1-Extensions/_compare/3f892f3b980850a2d43f6fa73a9bdb0b0e5e59f1...7187bb12f61beae458c51d1a43245ad687861fea) corresponds to your thoughts on this matter.
I wanted to keep track of previously recommended extensions, according to Thunderbird versions.

Cheers 👋

**Comment by HorlogeSkynet** [comment]
Yes why not, I think you even got permissions to edit the Wiki yourself if you want !

**Comment by atomGit** [comment]
i try to interact with GitHub as little as possible - as a result of Microsoft's acquisition i've moved my stuff to Codeberg - what M$ is doing here is very disturbing - the company has a very long history of anti-free software and now they are co-opting the development community in order to vacuum up data, train AI and for whatever other nefarious intents they have

**Comment by atomGit** [comment]
this just in...

[Sure, GitHub's AI-assisted Copilot writes code for you, but is it legal or ethical?](https://www.zdnet.com/article/is-github-copilots-code-legal-ethically-right/)

here's an excerpt...

> There's a rather large fly in the soup, though. There are legal questions about whether Codex had the right to use the open source code to provide the foundation of a proprietary service. And, even if it is legal, can Microsoft, OpenAI, and GitHub, and thus Copilot's users, ethically use the code it "writes?"
> 
> According to Nat Friedman, GitHub's CEO when [Copilot was released in beta](https://www.zdnet.com/article/microsoft-brings-ai-to-github-to-create-a-smart-programing-copilot-tool/), GitHub is legally in the clear because "[training ML systems on public data is fair use.](https://twitter.com/natfriedman/status/1409914420579344385)" But, he also noted, "IP [intellectual property] and AI will be an interesting policy discussion around the world in the coming years." You can say that again. 
> 
> Others venomously disagree. The [Software Freedom Conservancy (SFC)](https://sfconservancy.org/), a non-profit organization that provides legal services for open source software projects, holds the position that OpenAI was trained exclusively with GitHub-hosted projects. And many of these have been licensed under [copyleft](https://sfconservancy.org/copyleft-compliance/glossary.html#copyleft) licenses. Therefore, as Bradley M. Kuhn., the SFC's Policy Fellow and Hacker-in-Residence, [stated](https://sfconservancy.org/GiveUpGitHub/), "Most of those projects are not in the 'public domain,' they are licensed under [Free and Open Source Software (FOSS) licenses](https://opensource.org/licenses). These licenses have requirements including proper author attribution and, in the case of [copyleft licenses](https://copyleft.org/), they sometimes require that works based on and/or that incorporate the software be licensed under the same copyleft license as the prior work. Microsoft and GitHub have been ignoring these license requirements for more than a year."

**Comment by HorlogeSkynet** [comment]
Oh you really don't have to convince me on this, I am with you.
Please note that this very repo is personally mirrored here to deal with some of these concerns : https://git.forestier.app/HorlogeSkynet/thunderbird-user.js

Cheers :wave:

**Comment by atomGit** [comment]
i see a "sign in" link on git.forestier.app, but no "sign up" and i didn't see anything in the docs

**Comment by atomGit** [comment]
no need but thanks for offering
