### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by jakeafoster** [HorlogeSkynet/thunderbird-user.js#25]
Hi, thank you for providing thunderbird-user.js, it has been very helpful.

I believe there is a documentation error with 9110 (mail.tabs.autoHide). It says "**false**=Hides the tab bar if there is only one tab." It is the opposite. If **true**, then the tab bar will be hidden with one tab.

This is related to #21 where there was an extra bar added. If you set this variable to false, the extra bar (with 2+ tabs open) will be removed. This is the default experience.

I'm confused as to why this setting was changed in the first place though, I thought all changes were meant to be related to privacy and security but I don't think this affects any of that.

**Comment by HorlogeSkynet** [comment]
Hey @jakeafoster, many thanks for your message.

You're right, it actually seems like an _original_ oversight coming from here : https://github.com/arkenfox/user.js/issues/646#issuecomment-466434739.
I'll fix this for the v91 and v102 ESR branches, bye :wave:
