### ISSUE TITLE
[BUG] Can't download any attachment

### ISSUE THREAD

**Issue by Dupond** [HorlogeSkynet/thunderbird-user.js#26]
**Describe the bug**

Hello!

```javascript
/* 5002: disable memory cache
 * capacity: -1=determine dynamically (default), 0=none, n=memory capacity in kibibytes ***/
user_pref("browser.cache.memory.enable", false);
user_pref("browser.cache.memory.capacity", 0);
```

Those 2 prefs prevent me from downloading any attachment; I have to comment them out.

**Expected behavior**
The `thunderbird-user.js` file shouldn't prevent me from downloading an attachment.

**Environment**

- Thunderbird version used: at least from Thunderbird 91.2 up to 102.2.0
- `thunderbird user.js` template version used: version 91.2; the problem remains using the Thunderbird 102 ESR version #24
- Operating system and version: Arch Linux 5.19.6

**Checklist**
- [X] I can confirm the bug is due to `thunderbird user.js` **template** and not an overridden preference nor an add-on ;
- [X] I have searched for `[SETUP-*]` tags and read them up ;
- [X] I have searched the GitHub project (issues and Wiki) for my issue.

**Comment by HorlogeSkynet** [comment]
Hey back @Dupond !

That's strange, because I never had to tweak those to be able to download attachments (Windows and Linux).

Do you know if the issue is related to file extensions/MIME types ? i.e. the behavior is different depending on whether the file _could_ be handled by TB internal Web browser (.PDF, .SVG, .HTML, ...) ?
Do you know if Arch Linux packaging enforces any TB runtime hardening, causing the software to fallback on something which ends up depending on `browser.memory.cache` feature (tricky question) ?

Have you tried playing with `browser.download.forbid_open_with`, `browser.download.folderList` or even `browser.download.useDownloadDir` (an Android known-issue exists for the latter) ?
Same question with `browser.download.always_ask_before_handling_new_types` ? Maybe it is broken on some systems (?).

Thanks ! Bye 👋

**Comment by Dupond** [comment]
OK, that's a LOT of questions ;)

> Do you know if the issue is related to file extensions/MIME types ? i.e. the behavior is different depending on whether the file could be handled by TB internal Web browser (.PDF, .SVG, .HTML, ...) ?

No, it's not: it can't download *any* attachment. And if I click on a PDF attachment for example, it opens a new tab, but it stays blank. The PDF will never be displayed.

> Do you know if Arch Linux packaging enforces any TB runtime hardening, causing the software to fallback on something which ends up depending on browser.memory.cache feature (tricky question) ?

Arch Linux does add some custom files inside of the Thunderbird package (they do this with Firefox too):
- [usr/lib/thunderbird/defaults/pref/vendor-prefs.js](https://github.com/archlinux/svntogit-packages/blob/packages/thunderbird/trunk/vendor-prefs.js)
- [usr/lib/thunderbird/distribution/distribution.ini](https://github.com/archlinux/svntogit-packages/blob/packages/thunderbird/trunk/distribution.ini)
- and maybe a few other ones? You can check that [here](https://github.com/archlinux/svntogit-packages/tree/packages/thunderbird/trunk).

It doesn't seem to contain anything that could be related to my issue... What do you think?

> Have you tried playing with browser.download.forbid_open_with, browser.download.folderList or even browser.download.useDownloadDir (an Android known-issue exists for the latter) ?
Same question with browser.download.always_ask_before_handling_new_types ? Maybe it is broken on some systems (?).

I use Thunderbird 102.2.0 at the moment:
- I don't have `browser.download.forbid_open_with` nor `browser.download.folderList`
- `browser.download.useDownloadDir` is set to `false` (according to your `user.js` file)
- `browser.download.always_ask_before_handling_new_types` is set to `true` (following [this new pref](https://github.com/HorlogeSkynet/thunderbird-user.js/pull/24/commits/4dc99eb87ff407d605126f6bd13f704dbf0553bd#diff-417e8f625f16252f8ace3b0791d24c9b073d7394e9216c7b5d14a516d2572277R703)).

Should I try something else?

> EDIT : what actually happens when you try to download an attachment ? Just nothing, or maybe an error is thrown ?

A 34 Kio file (I don't know why 34 Kio exactly...) is created on my hard drive, and a message is displayed in the status bar of Thunderbird: "me@me.com: downloading messages..."

> Have you tried looking at the Web developer console for any "JavaScript" issue ?

No new message appears on the console when I try to download an attachment. But the console already contains a message (from the moment when Thunderbird is launched):

> gloda.datastore: got error in _asyncTrackerListener.handleError(): 19: constraint failed GlodaDatastore.jsm:1922:27
>     handleError resource:///modules/gloda/GlodaDatastore.jsm:1922

**Comment by HorlogeSkynet** [comment]
I haven't yet read the whole thread, but I think your issue is related to <https://bugzilla.mozilla.org/show_bug.cgi?id=1589649>.
Last message 14 days ago !

**Comment by Dupond** [comment]
I think you're right! So, since it's indeed a Thunderbird bug, I think this issue should be closed.

Thanx for your time investigating on this and answering!
