### ISSUE TITLE
[RFC] remove signon.rememberSignons

### ISSUE THREAD

**Issue by atomGit** [HorlogeSkynet/thunderbird-user.js#30]
this one just bit me :)

i might suggest removing `signon.rememberSignons`

if the user doesn't want TB to store passwords, they have that option and _not_ remembering passwords is the default, so i'm thinking there's probably no need for this pref

**Comment by HorlogeSkynet** [comment]
Hey @atomGit !

From what I see :

* this pref defaults to `true`, so I guess passwords _are_ saved by default
* I can't manage to find the corresponding setting from the UI (TB 102)
* unlike Firefox, it actually addresses browsing passwords, calendar authentication and even email accounts credentials (see [here](https://searchfox.org/comm-esr102/search?q=signon.rememberSignons&path=&case=false&regexp=false)

There doesn't seem to be a preference to _only_ disable browsing passwords saving, so yeah I guess it should be (at least) left commented ?

Bye 👋

**Comment by atomGit** [comment]
yeah, it's a little confusing perhaps...

the pref defaults to 'true', yes, but passwords (at least mail account passwords) still aren't remembered by default - when 'true' and you set up a mail account and access it, you're asked for the password

* if the pref is 'false', the user is not given a choice to remember the password and must enter it every time
* if the pref is 'true', an extra checkbox is displayed on the dialog asking to remember the password, but it is unchecked by default

and yeah, if you're going to dump it, just comment it out so the cleaner script can reset it - sorry, that's what i meant when i said 'remove'

**Comment by HorlogeSkynet** [comment]
Wow, that must be 100% confusing for "fresh" profiles then ! I'll reset it straightaway 🙇

**Comment by HorlogeSkynet** [comment]
Thanks again @atomGit 🙏
