### ISSUE TITLE
[RFC] What causes the "open link with..." dialog?

### ISSUE THREAD

**Issue by firefoxlover** [HorlogeSkynet/thunderbird-user.js#31]
## Problem
Clicking Links always results in a window, asking if I really want to open that link.
This is quite useless combined with cleaned HTML, as I wont click on any embedded image-links.

## Cant find the entry
I checked 
`browser.link.open_newwindow", 3`, 
but switching it to "0" does not change the behavior. (is "3" a bug? Comment says "Thunderbird only supports 0")

## what causes that popup, do you know that?

**Comment by HorlogeSkynet** [comment]
Hi @firefoxlover, it's `security.external_protocol_requires_permission`, added _here_ in TB v91.0 (https://github.com/HorlogeSkynet/thunderbird-user.js/commit/2d82b7cc0cfe432ccbb5c30656f5386cb53ef7f2).
The idea is not to prevent a click on embedded image-links, but mostly on URLs with schemes locally supported by a software installed system-wide.

Bye 👋

**Comment by firefoxlover** [comment]
Thank you!

**Comment by PhrozenByte** [comment]
Is there a way to disable this for `https` links only? IMHO it's extremely annoying to prompt for clicks on regular links (which should generally be safe), but requiring user interaction for any other protocol handler seems very reasonable. Is this possible?

Thanks for your project @HorlogeSkynet, keep up the great work! :heart:

**Comment by HorlogeSkynet** [comment]
Many thanks for your message Daniel :pray: 

Short answer : not for current ESR.

But I've been wandering across source code and I notice rather recent bug [1925479](https://bugzilla.mozilla.org/show_bug.cgi?id=1925479) followed by [1928826](https://bugzilla.mozilla.org/show_bug.cgi?id=1928826).
It appears `security.external_protocol_requires_permission` preference was planned for removal in TB 134, but it has been re-introduced with a slight difference, as it will [only address non-HTTP schemes](https://searchfox.org/comm-central/rev/a4c24c4f41b54c0d187734a2ebd8b2e4772becc4/mail/modules/LinkHelper.sys.mjs#87-90).

We _might_ consider a relax in future `user.js` releases, but IMHO it's also an affordable security safeguard for hazardous clicks in e-mail content, which could result in opening (hidden) malicious links... :slightly_smiling_face:

Bye :wave:

**Comment by HorlogeSkynet** [comment]
The "delayed timer" from this dialog seems to honor `security.dialog_enable_delay` hidden preference value.

**Comment by PhrozenByte** [comment]
> Short answer : not for current ESR.
> 
> But I've been wandering across source code and I notice rather recent bug [1925479](https://bugzilla.mozilla.org/show_bug.cgi?id=1925479) followed by [1928826](https://bugzilla.mozilla.org/show_bug.cgi?id=1928826). It appears `security.external_protocol_requires_permission` preference was planned for removal in TB 134, but it has been re-introduced with a slight difference, as it will [only address non-HTTP schemes](https://searchfox.org/comm-central/rev/a4c24c4f41b54c0d187734a2ebd8b2e4772becc4/mail/modules/LinkHelper.sys.mjs#87-90).

Excellent, thanks for the info! :+1: Looking forward to the next ESR.

> We _might_ consider a relax in future `user.js` releases, but IMHO it's also an affordable security safeguard for hazardous clicks in e-mail content, which could result in opening (hidden) malicious links... 🙂

I agree, `user.js` should rather follow the "better safe than sorry" principle. After individual consideration one can always disable it via `user-overrides.js`. What do you think about tagging `security.external_protocol_requires_permission` with `[SETUP-CHROME]`? Took me quite some time to find it and only thanks to this issue.

**Comment by HorlogeSkynet** [comment]
You're right, please see 7f756582828045fa33155130bde3a859be0efb55 :bow:
