### ISSUE TITLE
link fix

### ISSUE THREAD

**Issue by atomGit** [HorlogeSkynet/thunderbird-user.js#39]
hi!

ref: `github.com/HorlogeSkynet/thunderbird-user.js/wiki/1.1-Overview`

`https://12bytes.org/articles/tech/the-thunderbird-privacy-guide-for-dummies/` 
can be changed to:
`https://12bytes.org/the-thunderbird-privacy-guide-for-dummies/`

**Comment by HorlogeSkynet** [comment]
Thanks, [fixed](https://github.com/HorlogeSkynet/thunderbird-user.js/wiki/1.1-Overview/_compare/32796f67f1e7d80a1fd5cd2daf02ddb8a3bd3905...37ae086088e78919751211fee54fe3a32eb0958e).
