### ISSUE TITLE
[BUG] fix installation of Addons 

### ISSUE THREAD

**Issue by boredsquirrel** [HorlogeSkynet/thunderbird-user.js#43]
I have modified the use.js before adding it and restarting thunderbird, I commented this line out:

```
//user_pref("privacy.resistFingerprinting.block_mozAddonManager", false); // [HIDDEN PREF FF57-108]
```

But when trying to install an addon, instead it asks to download it. I am trying to find the cause of this.

I have the Theory that maybe RFP (which may not be needed if Thunderbird is not opening any websites) makes the store think it is not Thunderbird and thus not allow the install directly.

Or maybe its some mimehandler thing.

I am using the Thunderbird Flatpak on Linux, before adding the user.js Addon installs worked.

**Comment by HorlogeSkynet** [comment]
You must be right ! Nice catch, I haven't been able to nail this down in the past.
From personal experience, TB would download the .XCF and then it is possible to open it through TB and it will be handled properly.

As TB is an e-mail client, I _guess_ installing add-ons isn't usually done on a daily basis and it is an affordable loss of time ? 

Maybe we could add a `SETUP-FEATURE` tag ?

**Comment by trytomakeyouprivate** [comment]
> From personal experience, TB would download the .XCF and then it is possible to open it through TB and it will be handled properly.

Yes this is how it does it when it is broken. It is a workaround, and my main question is, if addon uppdates work, they should. Because if those dont work, this will break features, for example if an addon gets fixed or better adapted to the new 115 Supernova UI.

**Comment by HorlogeSkynet** [comment]
I think add-ons update works. Over the past years CardBook received theirs without any issue. But I'd love hearing other feedbacks on the matter.

About an add-ons "advice" list, I remember there is a wiki page dedicated to this (which could be improved and is opened to contributions).

About uBlock, last time I checked it was still broken for TB > 68 IIRC.

**Comment by trytomakeyouprivate** [comment]
[tb addon page](https://addons.thunderbird.net/en-US/thunderbird/addon/ublock-origin/)

[malwaretips forum on ublock on tb](https://malwaretips.com/threads/ublock-origin-is-now-available-for-thunderbird.122844/)

I think ublock is not necessary, as external images are always blocked and probably done differently.

Ublock would be total bloat, unless there is a list specifically for image loading or trackers in mails.

tbh I would losen the script up a bit, unless TB actively sets different defaults, but this will be a different issue. There is a lot of work to do ;D

**Comment by HorlogeSkynet** [comment]
Hey, sorry for the delay.

I agree with all of what I read above.

By "losen the script up" you mean about embedded images specifically ?

Would you like to contribute to wiki pages (at least the one about add-ons) ?

Thanks 🙏

**Comment by HorlogeSkynet** [comment]
Update : I've switched `privacy.resistFingerprinting.block_mozAddonManager` before restarting TB and... it didn't suffice to restore straightforward add-on installation from AMO :roll_eyes:

**Comment by HorlogeSkynet** [comment]
Hello @boredsquirrel, through dichotomy (and extensive) tests I managed to nail down this issue to three preferences. See [this wiki page section](https://github.com/HorlogeSkynet/thunderbird-user.js/wiki/4.1-Extensions#installing-extensions-from-amo-atn).
See you :wave:

**Comment by boredsquirrel** [comment]
very nice! thank you for your work!
