### ISSUE TITLE
[RFC] convert the script into modules

### ISSUE THREAD

**Issue by trytomakeyouprivate** [HorlogeSkynet/thunderbird-user.js#44]
It would be pretty easy to make the script load other scripts. That way we could split it up, as I think it mixes up thread models a lot.

a main script loading the modules (you can comment out the lines)
- general
- stay anonymous
- no html and images
- ...

best example is
- time zone
- dictionary
- time settings
- convert sender time to UTC

this does not make sense for many people, but instead would break workflows. Imagine Thunderbird in a company.

**Comment by HorlogeSkynet** [comment]
I'm rather in favor of keeping the template "close to" upstream, for maintainability purpose. Sorry if I seem boring about this, but the idea is to keep things simple as I have a pretty limited bandwidth.
