### ISSUE TITLE
Q: mailnews.display.html_as and UI View message body as

### ISSUE THREAD

**Issue by atomGit** [HorlogeSkynet/thunderbird-user.js#5]
before i dig into this, does anyone know offhand why none of the options in 'View -> Message Body As' are selected with this user.js?

according to my understanding, if you set `mailnews.display.html_as` to, for instance, '1', then the 'View -> Message Body As' option should be set to 'Plain Text', however none of the options are selected

the  `mailnews.display.html_as` pref value seems to work fine, i'm just curious why the value isn't reflected in the UI option - there must be another pref at play here

**Comment by HorlogeSkynet** [comment]
Yes, intrinsically related to `mailnews.display.prefer_plaintext` (someone externally reported me a strange behavior from TB around these prefs).

**Comment by atomGit** [comment]
i toggled that one and still no difference in the menu

**Comment by HorlogeSkynet** [comment]
Maybe related (or one of its pointers) : <https://bugzilla.mozilla.org/show_bug.cgi?id=592819>.

**Comment by HorlogeSkynet** [comment]
I've created and added a new `upstream` label for this kind of issues.
One may want to re-open this if one of the preferences set by the script is actually the root cause of the behavior.
