### ISSUE TITLE
[RFC] Local Mail autoconfig files

### ISSUE THREAD

**Issue by boredsquirrel** [HorlogeSkynet/thunderbird-user.js#51]
**Is your feature request related to a problem? Please describe.**
Afaik this hardening completely cripples the Feature of TB to use autoconfig for stuff like server ports, protocols etc.

I opened a PR, we can discuss if it makes sense.

I could not find any official info about this, but there is supposed to be a debian package, and [privacy handbuch](https://www.awxcnx.de/handbuch_31m) offers [a mail autoconfig dataset](https://privacy-handbuch.de/download/mailprovider-db.tar.bz2) for download, [which I now mirror on my Github repo](https://github.com/boredsquirrel/Thunderbird-hardening-automation/raw/main/mailprovider-db.tar.bz2)

I dont know where this needs to be placed, and how to test if it works. Maybe this allows to disable connections to the servers, and still autofetch the needed info?

**Describe alternatives you've considered**
Be a hackerman and know all ports and configs, or connect to some servers to fetch them.

**Additional context**
This is experimental and anecdotal but sounds useful. The dataset is quite nice, and I implemented it in some experimental form in [my script](https://github.com/boredsquirrel/Thunderbird-hardening-automation)

**Checklist**
- [x] I know `thunderbird user.js` is a **template** and personal preferences should be stored elsewhere ;
- [x] The change I want to propose should globally improve the `usability / ( privacy + security + anti-fingerprinting )` ratio ;
- [x] I agree that subsequent modifications to my change scope may occur in the future.

**Comment by HorlogeSkynet** [comment]
> I opened a PR, we can discuss if it makes sense.

It definitely makes sense, and would elegantly workarounds #50 if autoconfig stays disabled by default.

> I could not find any official info about this, but there is supposed to be a debian package [...]

Do you have any pointer about this ? A quick search in apt cache didn't return any results...

> Maybe this allows to disable connections to the servers, and still autofetch the needed info?

Yes, if we manage to _vendor_ the dataset and provide somehow a shim to make TB querying it.
Periodic or anniversary updates of the dataset has also to be considered.

Thanks for your time, bye :wave:

**Comment by boredsquirrel** [comment]
I dont use a Debian/Ubuntu system and the package is not in the Fedora repos.

tbh this seems to be very abandoned.

Having some possibly outdated settings may be better or worse than fetching from online sources.

**Comment by HorlogeSkynet** [comment]
> I dont use a Debian/Ubuntu system and the package is not in the Fedora repos.

Could you send me a resource where you first heard/read about this package ?

> Having some possibly outdated settings may be better or worse than fetching from online sources.

Indeed, and maybe we can afford "outdated settings" until next TB ESR version (for which we'll release a new version of this script accordingly afterwards).

Thanks ! Bye :pray:

**Comment by HorlogeSkynet** [comment]
I'm closing here as it's very unlikely something usable OOTB could be integrated _here_ at a minimal cost.
Although if such a project gets resuscitated, I think indeed it could be a viable alternative to auto-configuration (but "packaging" this template and the so-called database and script(s) would be required).

Thanks for your time and contributions, I hope you're okay with previously merged PR in their final states.
Bye :wave:

**Comment by boredsquirrel** [comment]
Thanks for your work!
