### ISSUE TITLE
[BUG] Unable to add Disroot account to Thunderbird

### ISSUE THREAD

**Issue by averagePedestrian** [HorlogeSkynet/thunderbird-user.js#54]
**Describe the bug**

I attempted to set up a Disroot email account in Thunderbird after applying the thunderbird-user.js configuration. My first attempt, without modifying any settings in the user.js file, failed with the error: 'Thunderbird failed to find the settings for your email account.'

For my second attempt, I adjusted the following preferences in the user.js file:

`network.cookie.cookieBehavior` to `1`
`network.http.referer.XOriginPolicy` to `0`
`network.http.sendRefererHeader` to `2`
`javascript.enabled` to `true`

I then tried to manually configure the server settings, but I encountered the same error.
I've included the console log below for reference.

[console-export.txt](https://github.com/user-attachments/files/16590175/console-export.txt)

**Expected behavior**

I expect Thunderbird to automatically detect and configure the correct server settings for my Disroot email account. If automatic detection fails, I should be able to manually enter the server settings and add the account without encountering any errors.

**Screenshots**

![thunderbird](https://github.com/user-attachments/assets/2dbc5a58-099a-4df5-861d-9a20b6ded848)

**Environment**

- Thunderbird version used (X.Y.Z) : 128.1.0
- `thunderbird user.js` template version used (X.Y or commit SHA) : 115.0
- Operating system and version : Windows 10 22H2

**Additional context**

**Checklist**

- [x] I can confirm the bug is due to `thunderbird user.js` **template** and not an overridden preference nor an add-on ;
- [x] I have searched for `[SETUP-*]` tags and read them up ;
- [x] I have searched the GitHub project (issues and Wiki) for my issue.

**Comment by HorlogeSkynet** [comment]
Hello @averagePedestrian,

There are different concerns that I can see from here :

Even if it may seem opinionated/unfortunate, this template disables TB "autoconfig" feature by default, for privacy reasons (see recent and almost-complete threads on the subject #51 & #50).
If you expect/want TB to automatically (try to) configure your Disroot (and maybe others) email accounts, you can always switch `mailnews.auto_config.guess.enabled` (`9101`) preference.

This being said, having "autoconfig" disabled isn't supposed to actually break connection to _any_ email servers, so I guess there is another issue here with the (manual) configuration you supplied.
From your error logs, I notice several `Hostname is empty or contains forbidden characters. Only letters, numbers, - and . are allowed.` messages.
Is there a possibility you copied/pasted server address, which could have contained a special character or something like that ?

About the other preferences you relaxed in an attempt to fix this/these issue(s), they are unrelated to email server setup (at this step) ; Although they may be interesting later, for instance if the login flow uses OAuth or depends on HTTP/JavaScript features (where provider's servers may enforce some security measures).

Good luck with this, keep us posted :pray:

**Comment by averagePedestrian** [comment]
@HorlogeSkynet In my latest attempt, I manually typed in all the account and server settings, but despite this, the account setup still failed.

**Comment by HorlogeSkynet** [comment]
@averagePedestrian so two questions remain : Have you tried with "autoconfig" enabled ? Does it work this way ?

By [looking at the code](https://searchfox.org/comm-central/source/mail/components/accountcreation/modules/Sanitizer.sys.mjs#97-115), it's very unlikely another error would be misleadingly caught here, causing log messages you experienced.

I also notice you use the latest 128 ESR, which I haven't (yet) migrated the template for.
I hope there isn't any incompatible/breaking preference causing you trouble here.

Thanks, bye :wave:

**Comment by averagePedestrian** [comment]
@HorlogeSkynet Yes, I've now tried with "autoconfig" enabled. I set `mailnews.auto_config.guess.enabled` to `true`, and it finally worked. With this, Thunderbird was able to automatically detect the correct server settings. Manual configuration also worked successfully.

**Comment by HorlogeSkynet** [comment]
So this was mystic yesterday 🙃
I guess you can switch "autoconfig" pref back and still rely on "manual" configuration...
I'm closing here as it doesn't seem related to template hardening.

Thanks for your time, bye 🙏
