### ISSUE TITLE
disabling acct. auto config repercussions

### ISSUE THREAD

**Issue by atomGit** [HorlogeSkynet/thunderbird-user.js#6]
when acct. auto config is disabled, as it is in user.js, you can't create a new mail acct. because the 'advanced config' button is disabled in the wizard

the solution is to enable offline mode and then run the new acct. wizard

is there a way around this?  because this could be a serious problem for users

**Comment by HorlogeSkynet** [comment]
Is that bottom-"disabled" what you mean ?

![Screenshot from 2019-12-22 16-55-23](https://user-images.githubusercontent.com/5331869/71324169-8bc71180-24d3-11ea-852e-e751196c085b.png)

I guess it is 'cause server configuration fields are already available, aren't they ?

**Comment by atomGit** [comment]
i'm not sure what you're asking - in your SS the "advanced config" and "done" buttons are disabled, so how does one create a new account when the only options are "cancel" and "re-test"?

if you set offline mode, then the "advanced config" becomes enabled and you can create the account, but that's not intuitive for new users

i brought up this issue because i'm not sure if it's another pref causing this (i doubt it) or if it's because it a dumb coding error in TB (likely)

if the problem is the latter, i think the description in the user.js regarding auto-config should be updated to let users know that the new acct. wizard will be unusable if acct. auto-config is disabled

**Comment by HorlogeSkynet** [comment]
Actually the "Done" button becomes enabled once the configuration is OK === Only once incoming and outgoing servers got **valid** (because tested on the go) configurations.
If you go offline, TB cannot test configurations so yeah, it allows you to skip this step.
The SS I posted had been obtained with the user.js installed, and new accounts can be created without going offline ¯\_ (ツ) _/¯

**Comment by atomGit** [comment]
i got ya
still, i think a breakage warning should be added to the 'README' section and [SECTION 6000] to let users know that it's one of those prefs that they a) might want to change and b) will break autoconfig

**Comment by HorlogeSkynet** [comment]
Hey @atomGit ! I'm sorry but I still don't get the breakage you are reporting.
I'm puzzled between `Can't reproduce` and `Don't get it`.

As server configuration fields are still available (and directly shown), I don't understand how disabling auto-configuration could break something :thinking:

Sorry again :confused:

**Comment by atomGit** [comment]
```
/** AUTO CONFIG ***/
/* 6001: Disable autoconfiguration
 * These options disable autoconfiguration of mail server settings in Thunderbird.
 * Such settings require a query to Mozilla which could have privacy implications
 * if the user wishes to keep the existance of the provider private
```

"existance" is spelled wrong :)

with auto-config disabled, the user has to fill in all (accurate) info when creating an account, as you said, but that may be a problem if they don't know, or don't want to bother gathering that info - i'm just suggesting that a [SETUP] tag be added so users know that auto-config will not work by default, same as the setup/warning  tags in item 3 of the ghacks user.js readme section at the top

when i said "break", i mean that auto-config is broken (it won't work) - bad choice of words perhaps

an adaptation of item 3 in the user.js for firefox could probably be added for this user.js as well since there's more than just these auto-config prefs that should be pointed out to the user - what do u think?

this all doesn't matter much to me, i'm just thinking of making it easier for users

**Comment by HorlogeSkynet** [comment]
(Yeah I've noticed that `existance` when looking at the script sooner today :rofl:)

Thanks for the explanation, I've (finally) understood.
So yeah, definitely a good idea. Would you be able to submit a PR _fixing_ this issue (as long as this ugly typo) ?

Bye :wave:

**Comment by atomGit** [comment]
> I've (finally) understood.

well, this adventure was largely my fault because i opened with "when acct. auto config is disabled [...] you can't create a new mail acct" which isn't entirely true as you made me aware of

i don't know how to do a PR - i think i have to fork the repo and then... something something something

given that [SETUP] tags could likely be applied to more than this issue, what i can do, if you want, is to go through the js and propose edits

**Comment by HorlogeSkynet** [comment]
> i don't know how to do a PR - i think i have to fork the repo and then... something something something

Don't worry, for the future (if you are interested) : <https://help.github.com/en/github/getting-started-with-github/fork-a-repo#keep-your-fork-synced> (as long as final further reading links).

Please see #7, and feel free to take over the proposals there.
Bye :wave:
