### ISSUE TITLE
[RFC] mailnews.headers.sendUserAgent

### ISSUE THREAD

**Issue by atomGit** [HorlogeSkynet/thunderbird-user.js#60]
hey there Horloge - is there any reason to send a UA, even minimal?

had a person contact me and suggest `mailnews.headers.sendUserAgent` be set to false

**Checklist**

- [X] I know `thunderbird user.js` is a **template** and personal preferences should be stored elsewhere ;
- [X] The change I want to propose should globally improve the `usability / ( privacy + security + anti-fingerprinting )` ratio ;
- [X] I agree that subsequent modifications to my change scope may occur in the future.

**Comment by HorlogeSkynet** [comment]
Hello @atomGit. So I've browsed [bug #1114475](https://bugzilla.mozilla.org/show_bug.cgi?id=1114475) which actually lead to `mailnews.headers.sendUserAgent` and `mailnews.headers.useMinimalUserAgent` preferences addition in TB 110, and indeed there is no strong arguments in actually sending UA nowadays.
I'll push a patch to disable this feature.
Thanks, bye :wave:

**Comment by HorlogeSkynet** [comment]
> Wouldn't this make you stick out/extra fingerprintable?

From [bug #1114475](https://bugzilla.mozilla.org/show_bug.cgi?id=1114475#c25), it appeared """[m]ost of them don't have that header, for example gmail and proton don't add them""".
We can hope for U-A not to be sent by default by TB in the future as well.
