### ISSUE TITLE
candidate prefs for [SETUP *] tag

### ISSUE THREAD

**Issue by atomGit** [HorlogeSkynet/thunderbird-user.js#8]
* 0302a: disable auto-INSTALLING Firefox updates
* 1223: enforce strict pinning (has warning tag, but there's no note in readme about warning tags)
* 6001: Disable autoconfiguration
* 6007: Address book collection
    * add setup tag, comment out, or leave as is?
* 6105: Check spelling before sending
* 6107: Send email in plaintext unless expressly overidden.
* 6108: Downgrade email to plaintext by default
* 6111: Prefer to view as plaintext or html
* 6112: Inline attachments

**Comment by HorlogeSkynet** [comment]
Yes ! Good catches.

What do you think about these :

* `[SETUP-SECURITY]`
* `[SETUP-COMPOSE]`
* `[SETUP-FEATURES]`

?

Same as #9, may we expect a PR for this too ?
Bye :wave:

**Comment by atomGit** [comment]
personally i think [SETUP] alone is sufficient, but that's up to you

re: pull requests...

> Anyone with read permissions to a repository can create a pull request, but you must have write permissions to create a branch. If you want to create a new branch for your pull request and don't have write permissions to the repository, you can fork the repository first.

do i have write perm? i don't think i want to be forking the repo in order to do PRs because then someone else stumbles upon it thinking it's the real deal when in fact it's an out of date copy

**Comment by HorlogeSkynet** [comment]
> personally i think [SETUP] alone is sufficient, but that's up to you

Oh yeah we may only use this one alone :man_shrugging:
But separating them down could be good, mostly if there are dozens of items to browse :roll_eyes:

> do i have write perm?

Yes you have.

> i don't think i want to be forking the repo in order to do PRs because then someone else stumbles upon it thinking it's the real deal when in fact it's an out of date copy

That's indeed a real problem in general, but (Microsoft's) GitHub lowers references forks, so it is mitigated.
Anyway, you may create a new branch (`git checkout -b <type_of_branch>/branch_name`), commit on it and then push it to this repository, before creating a Pull Request on `master`.

Keep me posted :wave:

**Comment by atomGit** [comment]
the whole 'git' thing is over my head - on the pull requests tab there's big green button that says 'new pull request' - what do i do from there?

**Comment by HorlogeSkynet** [comment]
Send me an email at `dev [at] samuel [dot] domains`, we'll take it from there without polluting this thread :wink:

**Comment by atomGit** [comment]
okeedokee - now that i have git working (thanks to your help), what do you want to do with these tags?

> But separating them down could be good, mostly if there are dozens of items

i sifted through the whole file and those were the only ones i felt could benefit from a tag - in the interest of keeping things super-simple for users, i vote we use only a [SETUP] tag - i think the pref description is enough to provide the extra information

that said, i can see the benefit of multiple tag types also, so it's your call

**Comment by HorlogeSkynet** [comment]
I was about to tell you that I'd be OK with only one tag, but looking again to the items you proposed, I really think separating them would be better (as they are definitely inherent to very distinct categories), at least for the future if we happen to add some more :man_shrugging:
